apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-04-20T01:47:48Z"
  generation: 1
  labels:
    app: part3
  name: part3
  namespace: default
  resourceVersion: "935"
  uid: e9cc7fbc-7395-42db-9550-16605f3b56e3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: part3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: part3
    spec:
      containers:
      - image: 9728054/part2:1.1
        name: image2-2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /app/conf.json
            subPath: conf.json
            name: config-map
      volumes:
        - name: config-map
          configMap:
            name: part3

status: {}